### ISSUE TITLE
Spawning in worldguard denied region

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDISWeepingAngels#10]
I have a region preventing hostile mobs from spawning in my spawn region.  This includes things like zombies, skeletons... and even armor_stands, but I believe that covers all of the entity types that your plugin uses to spawn these entities.  Is there possibly another entity type that I should be filtering out here?

Region flags like this:
```
    spawnmobprotect:
        min: {x: -300, y: 0, z: -300}
        max: {x: 300, y: 255, z: 300}
        members: {}
        flags:
            passthrough: allow
            damage-animals: deny
            deny-spawn: ['minecraft:pillager', 'minecraft:bat', 'minecraft:skeleton',
                'minecraft:illusioner', 'minecraft:phantom', 'minecraft:witch', 'minecraft:husk',
                'minecraft:ravager', 'minecraft:skeleton_horse', 'minecraft:snow_golem',
                'minecraft:cave_spider', 'minecraft:armor_stand', 'minecraft:enderman',
                'minecraft:silverfish', 'minecraft:stray', 'minecraft:vindicator',
                'minecraft:spider', 'minecraft:vex', 'minecraft:zombie', 'minecraft:creeper',
                'minecraft:drowned', 'minecraft:zombie_villager', 'minecraft:slime']
            mob-spawning: allow
        owners: {}
        type: cuboid
        priority: 10

```

With these settings it should only be possible for non-hostile mobs to spawn naturally.  Not sure if the weeping angel plugin spawns count as natural though.  I do know that you can still spawn hostiles using the /spawnmob command although NOT using the /summon command within this region.  Let me know if there's some way to accomplish this, thanks!

**Comment by eccentricdevotion** [comment]
Zombie Pigmen should also be in the list.
TWA monsters are not natural spawns, but the plugin does check the WorldGuard `MOB_SPAWNING` flag before trying to add a new monster. You have `mob-spawning: allow` so I'm not sure what the result will be...

**Comment by mrcoffee1026** [comment]
Ok, I'm sure there was once some reason I thought I needed that, but it's probably enough to simply remove that flag then.  I'll keep it off for now and see how that goes

**Comment by eccentricdevotion** [comment]
I guess you need `mob-spawning: allow` to let non-hostile mobs spawn?

**Comment by mrcoffee1026** [comment]
Maybe at some point I did, but I can't find a reason for keeping the flag explicitly set any longer.  Non hostiles certainly do still spawn even without this flag.  However, removing this flag doesn't stop the spawning of the weeping angels mobs... had a cyberman show up next to me not that long ago and that was after increasing the bounds of this region to +/- 450... it seems your plugin just completely bypasses the deny-spawn limitation.

Another plugin I have "boss mobs" just maintains a list of wg regions it won't spawn in... and allows you to select all defined regions as a blacklist if you want (excluding __global__ of course since there are other ways to stop spawning on worlds)... if that would be easier to implement, I would be happy with that as a solution also.

**Comment by eccentricdevotion** [comment]
Can you try build 152

**Comment by mrcoffee1026** [comment]
I'll likely have to wait till 1.16.2 is available on paper.  The recent build for 1.16.2 of TARDIS fails in paper 1.16.1 so this isn't likely to be compatible either.

**Comment by eccentricdevotion** [comment]
Just temporarily use Spigot...

**Comment by mrcoffee1026** [comment]
This does seem to properly function on Spigot 1.16.2, won't be able to attest to paper til 1.16.2 is a thing there, but unless that breaks it, this fixes it, thank you much!
