### ISSUE TITLE
Silurians in Siluria

### ISSUE THREAD

**Issue by karlredman** [eccentricdevotion/TARDISWeepingAngels#2]
Hi I'm working on building a 'universe' for my own game play. I love your TARDIS mods et al.

With the TARDIS generated Siluria world and WeepingAngles installed I'm receiving the following error message: "TARDISWeepingAngels cannot safely spawn Silurians in custom worlds!". 

I'm wondering if I've missed something somewhere with the configuration or if there is just a compatibility problem. Everything is working otherwise, i.e. Silurians do spawn in caves in my regular worlds.

Here are my server details:
Spigot server v12.2R2
TARDIS v3.8.3-b1716
TARDISChunkGenerator v2.5.6
TARDISWeepingAngels v2.4.2
TerrainControl v2.9.0-SNAPSHOT
LibsDisguises v9.5.2-SNAPSHOT
Multiverse-core v2.6.0
WorldEdit v6.1.9;caf0ad9
WorldGuard v6.2.1;84bc322
LuckPerms-Bukkit-4.2.74
ProtocolLib v4.4.0-SNAPSHOT-b403

Also, sorry if this is not the right place to post issues -I read somewhere that you wanted tickets in a particular place but I've lost that thread now...

**Comment by eccentricdevotion** [comment]
This is the best place, as Bukkit no longer sends me notifications...

**Comment by eccentricdevotion** [comment]
You should be able to ignore the warning, Silurians in Siluria are spawned via mob spawners in the Silurian buildings not by the TARDISWeepingAngels plugin.

**Comment by karlredman** [comment]
Ha! Thank you for the quick reply. 
Derp, I get it now. In hind sight I'm not sure why I thought the message would be an issue. Please consider this issue resolved. 

Thanks again.
