### ISSUE TITLE
region restrictions?

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDISWeepingAngels#3]
Any way we can add the ability to restrict spawning in certain regions using worldguard flags?  For example, I would like the tardis mobs to NOT spawn in the server's main spawn area, and have disabled the spawning of hostile mobs in spawn with flags like: deny-spawn: [minecraft:skeleton, minecraft:zombie] ... but the weeping angel mobs bypass these flags (even though they should PROBABLY count as the original vanilla mobs with disguises, they are not) and spawn everywhere.

**Comment by eccentricdevotion** [comment]
This should be done in build 108 and higher
45fb661
