### ISSUE TITLE
Strax transformation?

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDISWeepingAngels#6]
"If you manage to right-click a Sontaran with a 4 minute Weakness Potion before he kills you, he will transform into Strax."
If you right click with a 4-minute weakness potion... you consume it... so I'm not even confident that's the correct item mentioned.  Might this mean splash potion?   Although this... just like consuming the 4-minute weakness potion has no effect on the sontaran... except in the case of splash potion in which case he has potion particles while in his weakened state.

**Comment by eccentricdevotion** [comment]
250a809
Build 118 on the TARDIS Jenkins server

**Comment by mrcoffee1026** [comment]
Yey! He converts... doesn't seem to talk to you when right clicked though... that maybe just a failure of local testing though I'll try it on on the server later, thanks very much!

**Comment by eccentricdevotion** [comment]
SFX working here, though build 119 prevents double talking due to main and off hands both triggering speech

**Comment by mrcoffee1026** [comment]
I think I figured it out.. the resource packs... the "soundresourcepack" which i installed lastly, doesn't have the strax files listed in the sounds.json whereas they are in the weepingangels resource pack.  If I reverse the order I load those it should work for me again.  Thanks again!
