### ISSUE TITLE
weeping angels mobs bypass worldguard flags

### ISSUE THREAD

**Issue by mrcoffee1026** [eccentricdevotion/TARDISWeepingAngels#7]
such as ability to damage blocks... the toclafane can destroy blocks despite settings and there's no way to disable "build" for these creatures as there is for other mobs. (build 132)

**Comment by eccentricdevotion** [comment]
Should there be a check as to whether Judoon Guards can kill monsters in WorldGuard regions? Again what flag would need to be checked?

**Comment by mrcoffee1026** [comment]
maybe the mob-griefing setting? Though I would leave this enabled since disabling it ruins villagers. Although if they only would attack hostiles I don't think it would be strictly necessary; if they could also kill passive creatures like cats and tamed wolves then yes... since I would disable their ability if they could kill people's pets.

**Comment by eccentricdevotion** [comment]
Judoon only target hostile mobs - Blaze, Cave Spider, Creeper, Drowned, Elder Guardian, Enderman, Endermite, Evoker, Giant, Guardian, Husk, Illager, Illusioner, Pig Zombie, Pillager, Raider, Ravager, Silverfish, Skeleton, Spellcaster, Spider, Stray, Vex, Vindicator, Witch, Wither, Wither Skeleton, Zombie, Zombie Villager

**Comment by mrcoffee1026** [comment]
Oh sorry I didn't see your first question... I think it should be checking either all or at least obeying the same rule as the worldguard global setting (not a flag): "block-creeper-block-damage: true" ... if this is set to true, then it should prevent toclafanes or other mobs from damaging blocks with explosions as well.  Also the global setting "block-tnt-block-damage: true", it should follow this setting as well if it is using TNT for its explosion.  Since the judoon are targeting hostile mobs it should be fine... if a player tries to keep a pet zombie or something they'll have to make appropriate precautions for such a thing well outside of the normal realm of say... putting a fence around some sheep for protection, so I wouldn't worry about it.

**Comment by eccentricdevotion** [comment]
As far as I know WorldGuard global settings just apply the region flags to the whole world - https://worldguard.enginehub.org/en/latest/regions/global-region/
So the checks for CREEPER_EXPLOSION, TNT should still work as expected.
I'll do some checking

**Comment by mrcoffee1026** [comment]
I'm familiar with the global-region but these are not independent flags in the region _global_, they are settings made in the config.yml.  I'm not sure those settings are handled the same as flags as there are a lot of settings in there that can't be applied with flags... and any settings set in the config will override any flags set on a region as well.

**Comment by mrcoffee1026** [comment]
for example the "tnt" flag inside a region... if set to deny would prevent a PLAYER from placing/using tnt... but if a mob (like one from another plugin I have which can be equipped with TNT capabilities)  they would still be able to use TNT.  I can set the flag "creeper-explosion" to deny for a region even in the "_global_" region, but allowing the explosion while preventing it from damaging blocks can only be done through that config setting.

**Comment by eccentricdevotion** [comment]
I've found it's easy enough to check the WG config, so will add the checks.

**Comment by mrcoffee1026** [comment]
thank you so much!
