### ISSUE TITLE
mob heads

### ISSUE THREAD

**Issue by euanPC** [eccentricdevotion/TARDISWeepingAngels#9]
add in custom player heads which may drop when you kill dwo mobs

**Comment by eccentricdevotion** [comment]
You obviously want this feature as it's the third time you've asked about player heads...
I'm not convinced this feature is needed... or indeed how it should work.
Short requests like this are hardly ever implemented as there isn't enough detail to persuade me to add it.
Here is an example of a good issue: https://github.com/eccentricdevotion/TARDIS/issues/217
There is plenty of information about how the feature should work and why it is a "good thing" that benefits the plugin.
For this issue, you could at least attach example player heads that you think would be suitable, or offer an alternative like custom textured items that could be placed into item frames, or at least explain why you personally want the feature - how are you going to use these special drops?

**Comment by eccentricdevotion** [comment]
How about this?
Monster heads are a rare drop when you kill the monster - you can either just display them in an item frame, or equip them in your helmet slot. If you are wearing the head then the associated monster will not attack you.
Sounds like a good reason to actually implement this...

**Comment by euanPC** [comment]
yes

**Comment by euanPC** [comment]
http://minecraft.novaskin.me/gallery/tag/cyberman this also might be good for the cyberman

**Comment by euanPC** [comment]
and if you replace retextured items with mobehads it might save resources

**Comment by euanPC** [comment]
and if you replace retextured items with mobheads it could save resources

**Comment by eccentricdevotion** [comment]
I think the resources saved would be fairly small, either you load a resource pack texture or you load a player head texture, both involve loading something... and a resource pack is all clientside anyway.
IMHO player head textures look rubbish, I'm much happier with the higher resolution RP ones.
Besides, I've already added my suggestion above.

![cybermanheadvsmodel](https://user-images.githubusercontent.com/1841924/84011344-12ac6f80-a9ca-11ea-982f-a2ede691d7d4.png)
Head vs Model, I know which one I prefer.

**Comment by eccentricdevotion** [comment]
![monster_heads](https://user-images.githubusercontent.com/1841924/84012489-bcd8c700-a9cb-11ea-9eab-ef96a455c67a.jpg)

**Comment by euanPC** [comment]
could you make it a configurable setting

**Comment by euanPC** [comment]
for people who cant or wont have the texture pack

**Comment by euanPC** [comment]
like changing the retextured items in the hands to buttons to reduce visibility if the texture pack isnt installed

**Comment by eccentricdevotion** [comment]
Basically the plugin doesn't really work unless you have the resource pack installed, so I don't really see much point - might as well take advantage of it.

**Comment by euanPC** [comment]
but it does reduce the amount of servers that want to use it

**Comment by eccentricdevotion** [comment]
That's a non-issue, either a server uses it or they don't - it doesn't affect that it requires a resource pack to work
